version: '3'
services:
  npm-sum-service:
    build: "./sum-service"
    container_name: sum-service
    restart: always
    ports:
     - "3001:3000"
    networks:
     - "npm-microservices"
  npm-subtraction-service:
    build: "./subtraction-service"
    container_name: subtraction-service
    restart: always
    ports:
     - "3002:3000"
    networks:
     - "npm-microservices"
  npm-multiplication-service:
    build: "./multiplication-service"
    container_name: multiplication-service
    restart: always
    ports:
     - "3003:3000"
    networks:
     - "npm-microservices"
  npm-division-service:
    build: "./division-service"
    container_name: division-service
    restart: always
    ports:
     - "3004:3000"
    networks:
     - "npm-microservices"
  ui-service:
    build: "./ui-service"
    container_name: ui-service
    environment:
      - HOST_IP=localhost
    restart: always
    ports:
     - "3000:3000"
    networks:
     - "npm-microservices"
networks:
  npm-microservices: